all: main

main: spaceInvaders.cpp invadersWindows.hpp drawable.hpp ship.hpp empty.hpp invaders.hpp invadersWindows.cpp invadersBoard.hpp time.hpp invadersGame.hpp lives.hpp
	g++ spaceInvaders.cpp invadersWindows.cpp -o main -lncurses -lpanel
